version: '3.7'

services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: api-dev
        restart: unless-stopped
        environment:
            - PORT=$PORT
        volumes:
            - ./src:/app/src
            - ./tests:/app/tests
        ports:
            - '$PORT:3000'
        command: npm run dev:docker